authors:
  Misaki:
    name: Misaki
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/56343784?v=4
  Mireux:
    name: Mireux
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/88624709?v=4