authors:
  Misaki:
    name: Misaki
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/56343784?v=4
  Mireux:
    name: Mireux
    description: Creator
    avatar: https://github.com/squidfunk.png